name: auram_launcher
description: "Auram Launcher"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  arcane: ^6.5.9
  archive: ^4.0.7
  artifact: ^1.0.33
  toxic_flutter: ^1.1.0
  toxic: ^1.3.8
  microshaft: ^1.0.1
  url_launcher: ^6.3.2
  fast_log: ^1.0.7
  path_provider: ^2.1.5
  tinycolor2: ^3.0.1
dependency_overrides:
  skeletonizer: ^2.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  artifact_gen: ^1.3.7
  fire_crud_gen: ^1.1.4
flutter:
  uses-material-design: true
scripts:
  build_runner: flutter pub run build_runner build --delete-conflicting-outputs
  gen_launcher_icons: dart run flutter_launcher_icons
flutter_launcher_icons:
  ios: false
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"